# Generated by Django 6.0.3 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nlp_classification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
