# Generated by Django 6.0.3 on 2026-03-14 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('document', 'Document (PDF, Word)'), ('image', 'Image (JPG, PNG)'), ('video', 'Video'), ('note', 'Text Note'), ('financial', 'Financial Document'), ('social', 'Social Media Archive'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('content', models.TextField(blank=True, null=True)),
                ('privacy_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('sensitivity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('nlp_score', models.FloatField(default=0.0)),
                ('nlp_analyzed', models.BooleanField(default=False)),
                ('posthumous_action', models.CharField(choices=[('delete', 'Delete after death'), ('transfer', 'Transfer to beneficiary')], default='transfer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
